# Generated by Django 4.0 on 2021-12-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('identificacion', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('type_predio', models.CharField(choices=[('urbano', 'Urbano'), ('rural', 'Rural')], default='urbano', max_length=50)),
                ('matricula_inmobiliaria', models.CharField(max_length=250)),
                ('cedula_catastral', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('propietarios', models.ManyToManyField(blank=True, null=True, to='api.Propietario')),
            ],
        ),
    ]
