# Generated by Django 4.0 on 2021-12-21 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('predio', models.CharField(max_length=50)),
                ('matricula_inmobiliaria', models.IntegerField()),
                ('cedula_catastral', models.IntegerField()),
                ('propietarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.propietario')),
            ],
        ),
        migrations.AddField(
            model_name='propietario',
            name='predios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.predio'),
        ),
    ]
