# Generated by Django 4.0 on 2021-12-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_predio_propietario_predios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='predio',
            name='predio',
        ),
    ]
