# Generated by Django 4.0 on 2021-12-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tipo_predio_remove_predio_predio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tipo_Predio',
        ),
        migrations.AddField(
            model_name='predio',
            name='type_predio',
            field=models.CharField(choices=[('urbano', 'rural')], default='urbano', max_length=50),
        ),
    ]
