# Generated by Django 4.0 on 2021-12-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_tipo_predio_predio_type_predio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predio',
            name='type_predio',
            field=models.CharField(choices=[('urbano', 'Urbano'), ('rural', 'Rural')], default='urbano', max_length=50),
        ),
    ]
